# Generated by Django 4.0.3 on 2023-04-08 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitem',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
