# Generated by Django 4.2 on 2023-04-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_alter_carouselitem_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="carouselitem",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
